### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by sneakerhax**
Adding a Dockerfile for running this tool in a container

Instructions for building and running the container that can be added to the README file if you choose:

## Building with Docker

```
docker build -t hardcidr .
```

## Running with Docker

```
docker run -it hardcidr
┌──(root💀200c9d514198)-[/hardcidr]
└─# ./hardCIDR.sh
```

### CODE REVIEW

**Comment by bandrel** [comment]
@sneakerhax change the entrypoint so that it executes hardcidr directly

**Comment by bandrel** [comment]
`docker run -it -v $(pwd):/tmp --entrypoint './hardCIDR.sh' hardcidr:latest`

**Comment by sneakerhax** [comment]
Updated entrypoint

**Comment by bandrel** [comment]
@ninewires looks good. just make sure you add the `-v $(pwd):/tmp` to the readme or you wont be able to get the files.

**Comment by bandrel** [comment]
@sneakerhax update the docker file to use alpine. 
```
FROM bash:latest
RUN apk update
RUN apk add curl bind-tools
COPY . /app/
WORKDIR /app

ENTRYPOINT [ "/usr/local/bin/bash","/app/hardCIDR.sh" ]
```

**Comment by bandrel** [comment]
image

10 times smaller footprint for the container

**Review by bandrel — APPROVED** [review]

**Pull request merged**
